FROM openjdk:11
LABEL maintainer="javaguides.net"
ADD ./build/libs/OnlineTrainingPortalTrainer-0.0.1-SNAPSHOT.jar springboot-docker-demo.jar
#EXPOSE  8082
ENTRYPOINT ["java", "-jar", "springboot-docker-demo.jar"]